library/urls.py
from django.urls import path
from . import views

app_name = 'library'
urlpatterns = [
    path('',views.Home.as_view(), name = 'home'),
    path('SignUp/', views.SignUpPage.as_view(), name = 'SignUp'),
    path('Login/', views.LoginPage.as_view(), name = 'Login'),
    path('ConfirmLogout/',views.ConfirmLogout.as_view(), name='ConfirmLogout'),
    path('ConfirmLogout/Logout/', views.LogoutPage.as_view(), name = 'Logout'),
    path('SignUpPage/ConfirmUser/', views.user_confirm, name='UserCreateConfirm'),
    path('ListPage/', views.ListPage.as_view(), name = 'ListPage'),
    path('<int:pk>/', views.DetailView.as_view(), name = 'detail'),
    path('AddPage/', views.AddPage.as_view(), name = 'AddPage'),
    path('<int:pk>/EditPage', views.EditPage.as_view(), name = 'EditPage'),
    path('<int:pk>/DeletePage', views.DeletePage.as_view(), name='DeletePage'),
]

my_library/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('',include('library.urls')),
    path('admin/', admin.site.urls),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings


GENRE_CHOICES = (
    ('Literature','Literature'),
    ('Fiction','Fiction'),
    ('Non-Fiction','Non-Fiction'),
    ('Novel','Novel'),
    ('Poem','Poem'),
    ('Biography','Biography'),
    ('Science','Science'),
    ('Philosophy','Philosophy'),
    ('Art','Art'),
    ('Cinema','Cinema'),
    ('Religion','Religion'),
    ('Other','Other'),
)

class Book(models.Model):

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    author_name = models.CharField('Author Name',max_length=50, null = True, blank=True)
    author_surname = models.CharField('Author Surname',max_length=50)
    publisher = models.CharField(max_length=50, null=True, blank=True)
    genre = models.CharField(
        max_length = 20,
        choices = GENRE_CHOICES,
        default = 'Literature'
    )
    description = models.TextField(max_length=500, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    borrowed = models.BooleanField(default=False)

    class Meta:
        ordering = ['title']

    def get_absolute_url(self):
        return reverse("library:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.title}"

library/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'password1',
            'password2',
        )
        widgets = {
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = (
            'username'
            'password'
        )

library/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from .models import Book
from .forms import CustomUserCreationForm, UserLoginForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django import forms
from django.db.models import Q


class Home(generic.TemplateView):
    template_name = "library/index.html"

class SignUpPage(CreateView):
    template_name = 'library/user_form.html'
    model = User
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("library:UserCreateConfirm")
    def form_valid(self, form):
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        if User.objects.filter(username=username).exists():
            form.add_error('username', f'Username "{username}" is already in use.')
            return self.form_invalid(form)
        elif User.objects.filter(email=email).exists():
            form.add_error('email', f'Email "{email}" is already in use.')
            return self.form_invalid(form)
        
class LoginPage(LoginView):
    model = User
    form_class = UserLoginForm
    template_name = 'library/login_form.html'
    next_page = 'library:home'

class ConfirmLogout(generic.TemplateView):
    template_name = 'library/logout_form.html'

class LogoutPage(LogoutView):
    model = User
    template_name = 'library/logout_form.html'
    # next_page = 'library:home'

def user_confirm(request):
    return render(request,'library/user_creation_confirm.html')

class ListPage(LoginRequiredMixin, generic.ListView):
    template_name = "library/booklist.html"
    context_object_name = 'book_list'
    paginate_by = 10

    def get_queryset(self):
        q = self.request.GET.get('q') if self.request.GET.get('q') != None else ""
        p = int(self.request.GET.get('p')) if self.request.GET.get('p') != None else self.paginate_by
        self.paginate_by = p
        # self.set_pagination()
        book_list = Book.objects.filter(
            Q(user = self.request.user) & 
            (
                Q(title__icontains = q) |
                Q(author_surname__icontains = q) |
                Q(genre__icontains = q) |
                Q(publisher__icontains = q) |
                Q(description__icontains = q)        
            )
            
        ).values()
        return book_list
    
    def get_context_data(self, *args, **kwargs):
        context = super(ListPage,self).get_context_data(*args,**kwargs)
        q = self.request.GET.get('q') if self.request.GET.get('q') != None else ""
        p = int(self.request.GET.get('p')) if self.request.GET.get('p') != None else self.paginate_by
        context['query'] = q 
        context['pagination'] = p
        return context


class DetailView(generic.DetailView):
    model = Book
    template_name = "library/details.html"

class AddPage(CreateView):
    model = Book
    fields = [
        "title",
        "author_name",
        "author_surname",
        "publisher",
        "genre",
        "description",
        "borrowed",
    ]
    def form_valid(self, form: forms.BaseModelForm):
        form.instance.user = self.request.user
        return super().form_valid(form)

class EditPage(UpdateView):
    model = Book
    fields = [
        "title",
        "author_name",
        "author_surname",
        "publisher",
        "genre",
        "description",
        "borrowed",
    ]

class DeletePage(DeleteView):
    model = Book
    success_url = reverse_lazy("library:ListPage")

library/templates/library/book_confirm_delete.html
{% extends "library/master.html" %}

{% block title %}
Delete Book
{% endblock %}

{% block content %}

<div>
    <form method = 'POST' action = "{% url 'library:DeletePage' object.id %}">
        {% csrf_token %}
        <h3 class="container p-5 my-2 text-bg-warning text-center">Are you sure you want to delete "{{ object }}"</h3>
        {{form}}
        <div class="text-center">
            <input class="btn btn-success" type = "submit" value = "Confirm">
        <a class="btn btn-success" href ="{% url 'library:detail' object.id %}" role="button">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

library/templates/library/book_form.html
{% extends "library/master.html" %}

{% block title %}
Add Books
{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}

<div class="container pt-5">
    <form method = 'POST' action = "">
        {% csrf_token %}
        <div>
            {{form.as_p}}
            <input class="btn btn-primary" type = "submit" value = "Save">
            <a class="btn btn-primary" href ="{% url 'library:ListPage' %}" role="button">Cancel</a>
        </div>
    </form>
</div>

{% else %}
<h3 class="container p-5 my-2 text-bg-warning text-center">Please login to add books to your library</h3>
{% endif %}

{% endblock %}

library/templates/library/booklist.html
{% extends "library/master.html" %}

{% block title %}
Book List
{% endblock %}

{% block content %}
<form class="pt-2" method = "GET" action = "{% url 'library:ListPage' %}">
    <div class="container-fluid p-2 bg-primary">
        <input type = "text" name="q" placeholder="Search" value="{{query}}">
    </div>
</form>
<h1 class=".container-fluid text-center pt-5">Book List</h1>
<ul>
    {% for book in book_list %}
        <div class="container pt-3 list-group text-center" >
            <li class="list-group-item list-group-item-primary"><h4><a class="text-decoration-none" href = "{% url 'library:detail' book.id %}">{{book.title}}</a></h4>
            {% if book.author_name == null %}
                <p>Author: {{book.author_surname}}</p>
                <p> Publisher: {{book.publisher}}</p>
            {% else %}
                <p>Author: {{book.author_name}} {{book.author_surname}}</p>
                <p> Publisher: {{book.publisher}}</p>
            {% endif %}
            </li>
        </div>
    {% endfor %}
</ul>
<form method = "GET" action = "{% url 'library:ListPage' %}">
    <div class="container-fluid p-2 text-bg-secondary">
        <input type = "number" name="p" placeholder="5" min="1" value="{{pagination}}">
        <label for="p">Items in a page</label>
    </div>

</form>
<div class="pagination">
    <li class="step-links">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?q={{query}}&p={{pagination}}&page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?q={{query}}&p={{pagination}}&page={{ page_obj.previous_page_number }}">previous</a></li>
        {% endif %}

        <span class="current page-link active">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?q={{query}}&p={{pagination}}&page={{ page_obj.next_page_number }}">next</a></li>
            <li class="page-item"><a class="page-link" href="?q={{query}}&p={{pagination}}&page={{ page_obj.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
    </span>
</div>
{% endblock %}

library/templates/library/details.html
{% extends "library/master.html" %}

{% block title %}
{{ object.title }}
{% endblock %}

{% block content %}
<div class="container-fluid text-center p-5 text-bg-secondary">
    <h1>{{object.title}}</h1>
{% if book.author_name == null %}
    <p>Author: {{object.author_surname}}</p>
{% else %}
    <p>Author: {{object.author_name}} {{book.author_surname}}</p>
{% endif %}
<p> Publisher: {{object.publisher}}</p>
<p>Genre: {{ object.genre }}</p>
<p>{{ object.description }}</p>
{% if object.borrowed %}
    <p>BORROWED</p>
{% endif %}
<p>Date Added: {{ object.created }}</p>
<a class="btn btn-success" href = "{% url 'library:EditPage' object.id %}" role="button">Edit</a>
<a class="btn btn-success" href = "{% url 'library:DeletePage' object.id %}" role="button">Delete</a>
</div>

{% endblock %}

library/templates/library/index.html
{% extends "library/master.html" %}

{% block title %}
My Library
{% endblock %}

{% block content %}

<h2 class="container-fluid p-5 my-2 border text-center text-bg-success">Your online LIBRARY</h2>

{% endblock %}

library/templates/library/login_form.html
{% extends "library/master.html" %}

{% block title %}
Sign in
{% endblock %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<div class="container-fluid pt-3">
    <form class="form-control was-validated" method = 'POST'>
        {% csrf_token %}
        <div>
            {{form.as_p}}
            <input class="btn btn-primary" type = "submit" value = "Login">
            <a class="btn btn-primary" href ="{% url 'library:home' %}" role="button">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

library/templates/library/logout_form.html
{% extends "library/master.html" %}

{% block title %}
Logout
{% endblock %}

{% block content %}

<div>
    <form method = 'POST' action = "{% url 'library:Logout' %}">
        {% csrf_token %}
        <h3 class="container p-5 my-2 text-bg-warning text-center">"{{ request.user.username }}, please confirm to logout: "</h3>
        {{form}}
        <div class="text-center">
            <input class="btn btn-success" type = "submit" value = "Logout">
        <a class="btn btn-success" href ="{% url 'library:home' %}" role="button">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

library/templates/library/master.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
  <h1 class="container-fluid p-5 bg-primary text-white text-center">My Library</h1>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <div class="container-fluid justify-content-center">
      <ul class="navbar-nav nav-pills">
        <li class="nav-item"><a class="nav-link" href = "{% url 'library:home' %}">Home</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href = "{% url 'library:ListPage' %}">Book List</a></li>
        {% endif %}
        <li class="nav-item"><a class="nav-link" href = "{% url 'library:AddPage' %}">Add Book</a></li>
        {% if request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href = "{% url 'library:ConfirmLogout' %}">Logout</a></li>
        <li class="nav-item"><a class="btn btn-info" href=#>{{request.user.username}}</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href = "{% url 'library:Login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  {% if not request.user.is_authenticated %}
    <div class="container-fluid p-2">
      <a class="btn btn-success" href = "{% url 'library:SignUp' %}" role="button">Sign Up</a>
    </div>
  {% endif %}
{% block content %}
{% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

library/templates/library/user_creation_confirm.html
{% extends "library/master.html" %}

{% block title %}
User Created
{% endblock %}

{% block content %}
<div>
    <h3 class="container p-5 my-2 text-bg-warning text-center">User created successfully.</h3>
</div>
{% endblock %}

library/templates/library/user_form.html
{% extends "library/master.html" %}

{% block title %}
Add Books
{% endblock %}

{% block content %}

<div class="container-fluid pt-5">
    <form class="form-control was-validated" method = 'POST'>
        {% csrf_token %}
        <div>
            {{form.as_p}}
            <input class="btn btn-primary" type = "submit" value = "Register">
            <a class="btn btn-primary" href ="{% url 'library:home' %}" role="button">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}